/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Calculate_Magnetic_Moment_3D */

#ifndef _Included_Calculate_Magnetic_Moment_3D
#define _Included_Calculate_Magnetic_Moment_3D
#ifdef __cplusplus
extern "C" {
#endif
#undef Calculate_Magnetic_Moment_3D_grid
#define Calculate_Magnetic_Moment_3D_grid 10L
#undef Calculate_Magnetic_Moment_3D_m_ROuterFrom
#define Calculate_Magnetic_Moment_3D_m_ROuterFrom 0.2
#undef Calculate_Magnetic_Moment_3D_m_RMiddleFrom
#define Calculate_Magnetic_Moment_3D_m_RMiddleFrom 0.9
#undef Calculate_Magnetic_Moment_3D_m_RInnerFrom
#define Calculate_Magnetic_Moment_3D_m_RInnerFrom 2.5
#undef Calculate_Magnetic_Moment_3D_GAMMARBAR
#define Calculate_Magnetic_Moment_3D_GAMMARBAR 42.58
/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    setmVariables
 * Signature: (IDDDDDD)V
 */
JNIEXPORT void JNICALL Java_Calculate_1Magnetic_1Moment_13D_setmVariables
  (JNIEnv *, jobject, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    setMagMoment
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_Calculate_1Magnetic_1Moment_13D_setMagMoment
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    setBackPhase
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_Calculate_1Magnetic_1Moment_13D_setBackPhase
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    setRealImagNumbers
 * Signature: ([[[F[[[F)V
 */
JNIEXPORT void JNICALL Java_Calculate_1Magnetic_1Moment_13D_setRealImagNumbers
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    setXYZ
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_Calculate_1Magnetic_1Moment_13D_setXYZ
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    setPhaseXYMatrix
 * Signature: ([[F)V
 */
JNIEXPORT void JNICALL Java_Calculate_1Magnetic_1Moment_13D_setPhaseXYMatrix
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    setPhaseXZMatrix
 * Signature: ([[F)V
 */
JNIEXPORT void JNICALL Java_Calculate_1Magnetic_1Moment_13D_setPhaseXZMatrix
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    setMagXYMatrix
 * Signature: ([[F)V
 */
JNIEXPORT void JNICALL Java_Calculate_1Magnetic_1Moment_13D_setMagXYMatrix
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    setMagXZMatrix
 * Signature: ([[F)V
 */
JNIEXPORT void JNICALL Java_Calculate_1Magnetic_1Moment_13D_setMagXZMatrix
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    setSmallBox
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_Calculate_1Magnetic_1Moment_13D_setSmallBox
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    setCenterL
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_Calculate_1Magnetic_1Moment_13D_setCenterL
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    setCenterM
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_Calculate_1Magnetic_1Moment_13D_setCenterM
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    setCenterS
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_Calculate_1Magnetic_1Moment_13D_setCenterS
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    setmR123
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_Calculate_1Magnetic_1Moment_13D_setmR123
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    setR123PhaseCalc
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_Calculate_1Magnetic_1Moment_13D_setR123PhaseCalc
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    setMagMomentVariables
 * Signature: (DDDDDD)V
 */
JNIEXPORT void JNICALL Java_Calculate_1Magnetic_1Moment_13D_setMagMomentVariables
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    setRi
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_Calculate_1Magnetic_1Moment_13D_setRi
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    setStep6Variables
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_Calculate_1Magnetic_1Moment_13D_setStep6Variables
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    setSimulatedMatrices
 * Signature: ([[[FI)V
 */
JNIEXPORT void JNICALL Java_Calculate_1Magnetic_1Moment_13D_setSimulatedMatrices
  (JNIEnv *, jobject, jobjectArray, jint);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    removeBackgroundPhase
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_Calculate_1Magnetic_1Moment_13D_removeBackgroundPhase
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    generateSubpixelArray
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Calculate_1Magnetic_1Moment_13D_generateSubpixelArray
  (JNIEnv *, jobject);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    estimateSubpixelCenter
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Calculate_1Magnetic_1Moment_13D_estimateSubpixelCenter
  (JNIEnv *, jobject);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    calculateRealSum
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Calculate_1Magnetic_1Moment_13D_calculateRealSum
  (JNIEnv *, jobject);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    calculateImagSum
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Calculate_1Magnetic_1Moment_13D_calculateImagSum
  (JNIEnv *, jobject);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    estBkgAndSpinDensity
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Calculate_1Magnetic_1Moment_13D_estBkgAndSpinDensity
  (JNIEnv *, jobject);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    calcSusceptibility
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Calculate_1Magnetic_1Moment_13D_calcSusceptibility
  (JNIEnv *, jobject);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    interpolateVoxelsSIM
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Calculate_1Magnetic_1Moment_13D_interpolateVoxelsSIM
  (JNIEnv *, jobject, jint);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    SumCircleElementsReal3DSIMMED
 * Signature: (IIII)D
 */
JNIEXPORT jdouble JNICALL Java_Calculate_1Magnetic_1Moment_13D_SumCircleElementsReal3DSIMMED
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    equation10
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_Calculate_1Magnetic_1Moment_13D_equation10
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    calculateUncertainty
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_Calculate_1Magnetic_1Moment_13D_calculateUncertainty
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    getSpinDensity
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Calculate_1Magnetic_1Moment_13D_getSpinDensity
  (JNIEnv *, jobject);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    getBkg
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Calculate_1Magnetic_1Moment_13D_getBkg
  (JNIEnv *, jobject);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    getSubX
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Calculate_1Magnetic_1Moment_13D_getSubX
  (JNIEnv *, jobject);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    getSubY
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Calculate_1Magnetic_1Moment_13D_getSubY
  (JNIEnv *, jobject);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    getSubZ
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Calculate_1Magnetic_1Moment_13D_getSubZ
  (JNIEnv *, jobject);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    getSubXOther
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Calculate_1Magnetic_1Moment_13D_getSubXOther
  (JNIEnv *, jobject);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    getSubYOther
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Calculate_1Magnetic_1Moment_13D_getSubYOther
  (JNIEnv *, jobject);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    getSubZOther
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Calculate_1Magnetic_1Moment_13D_getSubZOther
  (JNIEnv *, jobject);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    calculateMagneticMoment
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Calculate_1Magnetic_1Moment_13D_calculateMagneticMoment
  (JNIEnv *, jobject);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    getMR1Calc
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Calculate_1Magnetic_1Moment_13D_getMR1Calc
  (JNIEnv *, jobject);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    getMR2Calc
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Calculate_1Magnetic_1Moment_13D_getMR2Calc
  (JNIEnv *, jobject);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    getMR3Calc
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Calculate_1Magnetic_1Moment_13D_getMR3Calc
  (JNIEnv *, jobject);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    getSNR
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Calculate_1Magnetic_1Moment_13D_getSNR
  (JNIEnv *, jobject);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    getE12
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Calculate_1Magnetic_1Moment_13D_getE12
  (JNIEnv *, jobject);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    getE23
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Calculate_1Magnetic_1Moment_13D_getE23
  (JNIEnv *, jobject);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    getB0
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Calculate_1Magnetic_1Moment_13D_getB0
  (JNIEnv *, jobject);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    getTE
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Calculate_1Magnetic_1Moment_13D_getTE
  (JNIEnv *, jobject);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    getRChi
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Calculate_1Magnetic_1Moment_13D_getRChi
  (JNIEnv *, jobject);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    getRho
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Calculate_1Magnetic_1Moment_13D_getRho
  (JNIEnv *, jobject);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    getChi
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Calculate_1Magnetic_1Moment_13D_getChi
  (JNIEnv *, jobject);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    getA
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Calculate_1Magnetic_1Moment_13D_getA
  (JNIEnv *, jobject);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    getUncertainty
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Calculate_1Magnetic_1Moment_13D_getUncertainty
  (JNIEnv *, jobject);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    getP
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Calculate_1Magnetic_1Moment_13D_getP
  (JNIEnv *, jobject);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    getP0
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Calculate_1Magnetic_1Moment_13D_getP0
  (JNIEnv *, jobject);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    getMagMoment
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Calculate_1Magnetic_1Moment_13D_getMagMoment
  (JNIEnv *, jobject);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    getResX
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Calculate_1Magnetic_1Moment_13D_getResX
  (JNIEnv *, jobject);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    getResY
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Calculate_1Magnetic_1Moment_13D_getResY
  (JNIEnv *, jobject);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    getResZ
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Calculate_1Magnetic_1Moment_13D_getResZ
  (JNIEnv *, jobject);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    getRealSum
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Calculate_1Magnetic_1Moment_13D_getRealSum
  (JNIEnv *, jobject);

/*
 * Class:     Calculate_Magnetic_Moment_3D
 * Method:    getImagSum
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Calculate_1Magnetic_1Moment_13D_getImagSum
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
